spring.application.name=psp-simulator

server.port=8083


#spring.autoconfigure.exclude=\
#org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
#org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
#org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/psp_db
spring.datasource.username=psp_service
spring.datasource.password=test3
