spring.application.name=ledger-service
server.port=8081


#spring.autoconfigure.exclude=\
#org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
#org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
#org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=ledger_service
spring.datasource.password=test1

spring.flyway.user=flyway_user
spring.flyway.password=test4

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.group.readiness.include=readinessState,db