spring.application.name=orchestrator
server.port=8082


#spring.autoconfigure.exclude=\
#org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
#org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
#org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/orchestrator_db
spring.datasource.username=orchestrator_service
spring.datasource.password=test2